-- Run once in Supabase SQL Editor on a new project.
-- Existing MySQL data is not copied by this schema/seed file.
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('admin', 'customer')),
    profile_picture TEXT,
    address TEXT NOT NULL,
    phone VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON users (LOWER(email));

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category_type TEXT NOT NULL CHECK (category_type IN ('liquid', 'solid')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS categories_name_lower_unique ON categories (LOWER(name));

CREATE TABLE IF NOT EXISTS medicines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category_id INTEGER REFERENCES categories(id),
    vendor_name VARCHAR(100) NOT NULL,
    price NUMERIC(10,2) NOT NULL CHECK (price > 0),
    availability INTEGER NOT NULL DEFAULT 0 CHECK (availability >= 0),
    description TEXT,
    image_path TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    medicine_id INTEGER NOT NULL REFERENCES medicines(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, medicine_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    total_amount NUMERIC(10,2) NOT NULL CHECK (total_amount >= 0),
    shipping_address TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled')),
    payment_method VARCHAR(50),
    order_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    medicine_id INTEGER NOT NULL REFERENCES medicines(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0)
);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    amount NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
    payment_method VARCHAR(50) NOT NULL,
    transaction_id VARCHAR(100),
    payment_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categories (name, category_type) VALUES
    ('Aspirin genre', 'solid'),
    ('Paracetamol genre', 'solid'),
    ('Cough Syrup genre', 'liquid')
ON CONFLICT (name) DO NOTHING;

INSERT INTO medicines (name, category_id, vendor_name, price, availability, description)
SELECT 'Napa 500', id, 'Beximco Pharma', 12.00, 120, 'Paracetamol tablet'
FROM categories WHERE name = 'Paracetamol genre'
AND NOT EXISTS (SELECT 1 FROM medicines WHERE name = 'Napa 500');

INSERT INTO medicines (name, category_id, vendor_name, price, availability, description)
SELECT 'Aspirin Protect', id, 'Bayer', 80.00, 50, 'Aspirin tablet'
FROM categories WHERE name = 'Aspirin genre'
AND NOT EXISTS (SELECT 1 FROM medicines WHERE name = 'Aspirin Protect');

INSERT INTO medicines (name, category_id, vendor_name, price, availability, description)
SELECT 'Dexo Cough Syrup', id, 'Square Pharma', 95.00, 35, 'Liquid cough syrup'
FROM categories WHERE name = 'Cough Syrup genre'
AND NOT EXISTS (SELECT 1 FROM medicines WHERE name = 'Dexo Cough Syrup');

-- The PHP server connects directly to Postgres. No browser/Data API policies
-- are needed; enabling RLS protects these tables from anon/authenticated API keys.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Default administrator for the course/demo deployment.
-- Change this password after the first successful login in a real deployment.
INSERT INTO users (name, email, password_hash, role, address, phone, profile_picture)
SELECT 'Site Admin', 'asadbinjafor@gmail.com',
       '$2y$10$wa2k1wEjstjfm.3BvkxdUuFh8mOrGhAMvxQuHUmTz5TVkDB2Ebx6S',
       'admin', 'Dhaka', '00000000000', ''
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE LOWER(email) = LOWER('asadbinjafor@gmail.com')
);

-- Re-running this file also repairs the role/password of the default admin.
UPDATE users
SET role = 'admin',
    password_hash = '$2y$10$wa2k1wEjstjfm.3BvkxdUuFh8mOrGhAMvxQuHUmTz5TVkDB2Ebx6S'
WHERE LOWER(email) = LOWER('asadbinjafor@gmail.com');
